In [1]:
import geopandas as gpd

In [2]:
gdf_1 = gpd.read_file(r"D:\Work\WB\LDT\countries\UZB\gadm41_UZB_1.json")
gdf_2 = gpd.read_file(r"D:\Work\WB\LDT\countries\UZB\gadm41_UZB_2.json")

In [3]:
gdf_1

,GID_1,GID_0,COUNTRY,NAME_1,VARNAME_1,NL_NAME_1,TYPE_1,ENGTYPE_1,CC_1,HASC_1,ISO_1,geometry
0,UZB.1_1,UZB,Uzbekistan,Andijon,Andijan|Andizhan,NA,Wiloyat,Region,NA,UZ.AN,UZ-AN,"MULTIPOLYGON (((72.392 40.4034, 72.3753 40.401..."
1,UZB.2_1,UZB,Uzbekistan,Buxoro,Bukhoro|Bukhara|Mawarranahr|Tran,NA,Wiloyat,Region,NA,UZ.BU,UZ-BU,"MULTIPOLYGON (((64.7782 39.7615, 64.7913 39.74..."
2,UZB.3_1,UZB,Uzbekistan,Farg'ona,Farghona|Fergana|Ferghana,NA,Wiloyat,Region,NA,UZ.FA,UZ-FA,"MULTIPOLYGON (((71.211 39.9312, 71.2102 39.928..."
3,UZB.4_1,UZB,Uzbekistan,Jizzax,Dzhizak|Jizzakh,NA,Wiloyat,Region,NA,UZ.JI,UZ-JI,"MULTIPOLYGON (((67.7576 39.6424, 67.7137 39.65..."
4,UZB.8_1,UZB,Uzbekistan,Namangan,NA,NA,Wiloyat,Region,NA,UZ.NG,UZ-NG,"MULTIPOLYGON (((71.5771 40.8199, 71.5649 40.80..."
5,UZB.9_1,UZB,Uzbekistan,Navoiy,Navoi,NA,Wiloyat,Region,NA,UZ.NW,UZ-NW,"MULTIPOLYGON (((66.2459 40.1469, 66.2218 40.11..."
6,UZB.5_1,UZB,Uzbekistan,Qaraqalpaqstan,Karakalpakstan|Qoraqalpog`iston,NA,Repuplikasi,AutononousRegion,NA,UZ.QR,NA,"MULTIPOLYGON (((61.4051 41.2186, 61.3962 41.20..."
7,UZB.6_1,UZB,Uzbekistan,Qashqadaryo,Kashkadarya|Kashka-Dar'ya|Kashka,NA,Wiloyat,Region,NA,UZ.QA,UZ-QA,"MULTIPOLYGON (((66.6015 38.0238, 66.5656 38.03..."
8,UZB.10_1,UZB,Uzbekistan,Samarqand',Samarkand,NA,Wiloyat,Region,NA,UZ.SA,NA,"MULTIPOLYGON (((67.4939 39.3208, 67.4853 39.32..."
9,UZB.11_1,UZB,Uzbekistan,Sirdaryo,Syr-Dar'ya,NA,Wiloyat,Region,NA,UZ.SI,UZ-SI,"MULTIPOLYGON (((69.1087 40.2129, 69.0859 40.21..."
10,UZB.12_1,UZB,Uzbekistan,Surxondaryo,Surkhandarya|Sukhan-Dar'ya|Surxo,NA,Wiloyat,Region,NA,UZ.SU,UZ-SU,"MULTIPOLYGON (((67.7727 37.2079, 67.7539 37.22..."
11,UZB.14_1,UZB,Uzbekistan,Toshkent,Taschkent|Tashkent,NA,Wiloyat,Region,NA,UZ.TA,UZ-TK,"MULTIPOLYGON (((69.2526 40.5614, 69.2352 40.55..."
12,UZB.13_1,UZB,Uzbekistan,ToshkentShahri,TashkentCity|ToshkentCity,NA,Shahar,City,NA,UZ.TK,NA,"MULTIPOLYGON (((69.3365 41.2502, 69.3111 41.23..."
13,UZB.7_1,UZB,Uzbekistan,Xorazm,Khorezm|Khiva|Khwarazm|Khorazm,NA,Wiloyat,Region,NA,UZ.KH,UZ-XO,"MULTIPOLYGON (((62.1242 40.5817, 62.1104 40.60..."

In [4]:
gdf_2

,GID_2,GID_0,COUNTRY,GID_1,NAME_1,NL_NAME_1,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,UZB.1.1_1,UZB,Uzbekistan,UZB.1_1,Andijon,NA,Andijon,Andijan,NA,District,District,NA,UZ.AN.AJ,"MULTIPOLYGON (((72.3441 40.661, 72.3336 40.657..."
1,UZB.1.2_1,UZB,Uzbekistan,UZB.1_1,Andijon,NA,Asaka,NA,NA,District,District,NA,UZ.AN.AD,"MULTIPOLYGON (((72.3002 40.7221, 72.3087 40.70..."
2,UZB.1.3_1,UZB,Uzbekistan,UZB.1_1,Andijon,NA,Baliqchi,Baliqchi,NA,District,District,NA,UZ.AN.BA,"MULTIPOLYGON (((71.9361 40.7658, 71.8869 40.76..."
3,UZB.1.4_1,UZB,Uzbekistan,UZB.1_1,Andijon,NA,Bo'zsuv,Boz,NA,District,District,NA,UZ.AN.BO,"MULTIPOLYGON (((71.8869 40.7694, 71.9361 40.76..."
4,UZB.1.5_1,UZB,Uzbekistan,UZB.1_1,Andijon,NA,Buloqboshi,Buloqboshi,NA,District,District,NA,UZ.AN.BU,"MULTIPOLYGON (((72.5233 40.5527, 72.5165 40.55..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,UZB.7.6_1,UZB,Uzbekistan,UZB.7_1,Xorazm,NA,Urganch,Urgench,NA,District,District,NA,UZ.KH.UD,"MULTIPOLYGON (((60.6783 41.7692, 60.7054 41.75..."
157,UZB.7.7_1,UZB,Uzbekistan,UZB.7_1,Xorazm,NA,Xiva,Khiva,NA,City,City,NA,UZ.KH.XC,"MULTIPOLYGON (((60.4242 41.2409, 60.3993 41.25..."
158,UZB.7.8_1,UZB,Uzbekistan,UZB.7_1,Xorazm,NA,Xonqa,Khanka,NA,District,District,NA,UZ.KH.XO,"MULTIPOLYGON (((60.8762 41.5903, 60.8848 41.57..."
159,UZB.7.9_1,UZB,Uzbekistan,UZB.7_1,Xorazm,NA,Yangiariq,Yangiaryk,NA,District,District,NA,UZ.KH.YR,"MULTIPOLYGON (((60.6085 41.2241, 60.5809 41.22..."
160,UZB.7.10_1,UZB,Uzbekistan,UZB.7_1,Xorazm,NA,Yangibozor,Yangibazar,NA,District,District,NA,UZ.KH.YB,"MULTIPOLYGON (((60.5971 41.8252, 60.6124 41.82..."

In [5]:
gdf_2['ENGTYPE_2'].value_counts()

ENGTYPE_2
District     140
City          20
Waterbody      1
Name: count, dtype: int64

In [3]:
import cdsapi

dataset = "reanalysis-era5-single-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": [
        "2m_temperature",
        "total_precipitation"
    ],
    "year": ["2023", "2024"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "01:00", "02:00",
        "03:00", "04:00", "05:00",
        "06:00", "07:00", "08:00",
        "09:00", "10:00", "11:00",
        "12:00", "13:00", "14:00",
        "15:00", "16:00", "17:00",
        "18:00", "19:00", "20:00",
        "21:00", "22:00", "23:00"
    ],
    "data_format": "netcdf",
    "download_format": "zip",
    "area": [45.5868043076, 55.9289172707, 37.1449940049, 73.055417108]
}

target = r"D:\Work\WB\LDT\countries\UZB/payload.zip"

client = cdsapi.Client()
client.retrieve(dataset, request, target).download()

2025-02-13 22:28:49,444 INFO [2024-09-26T00:00:00] Watch our [Forum](https://forum.ecmwf.int/) for Announcements, news and other discussed topics.
2025-02-13 22:28:49,444 WARNING [2024-06-16T00:00:00] CDS API syntax is changed and some keys or parameter names may have also changed. To avoid requests failing, please use the "Show API request code" tool on the dataset Download Form to check you are using the correct syntax for your API request.
2025-02-13 22:28:50,523 INFO Request ID is 41f6d9b4-b8d4-426e-9831-cfc10842e6bb
2025-02-13 22:28:50,869 INFO status has been updated to accepted
2025-02-13 22:37:15,481 INFO status has been updated to successful

9c36ce1a21f8757993f90ca38434d84a.zip:   0%|          | 0.00/119M [00:00<?, ?B/s]

AttributeError: 'str' object has no attribute 'download'

In [4]:
import rioxarray as rxr

ds = rxr.open_rasterio(r"C:\Users\sonle\Downloads\9c36ce1a21f8757993f90ca38434d84a\data_stream-oper_stepType-instant.nc")

In [ ]:
ds.sel(valid_time="2023-01-01").rio.to_raster(r"C:\Users\sonle\Downloads\9c36ce1a21f8757993f90ca38434d84a\test.tiff")

SyntaxError: invalid syntax (3558572169.py, line 1)