In [21]:
import pandas as pd
import numpy as np
import xarray as xr
import rioxarray as rxr
import rasterio
import glob
import geopandas as gpd
from tqdm import tqdm_notebook
import pandas as pd
from rasterstats import zonal_stats

import sys
sys.path.append("D:\Work\WB\LDT")

from src.dhelper import get_month_range

In [22]:
poly = gpd.read_file('D:\Work\WB\LDT\countries\SRB\shapefiles\gadm41_SRB_2.json')
poly = poly.to_crs(epsg=4326)
poly = poly[['GID_2', 'geometry']]

In [24]:
yms = get_month_range('2018-01', '2024-12', input_format="%Y-%m", output_format="%Y-%m")

dfs = []

for ym in tqdm_notebook(yms):
    df_poly = poly.copy(deep=True)
    lumi = zonal_stats(poly.geometry, 
                rf"D:\Work\WB\LDT\countries\SRB\raw_data\luminosity\SRB_bm_{ym}.tif",
                stats=['sum'])
    
    df_poly['ym'] = ym
    df_poly['year'] = df_poly['ym'].str[:4]
    df_poly['luminosity'] = pd.DataFrame(lumi)

    dfs.append(df_poly)

C:\Users\sonle\AppData\Local\Temp\ipykernel_2012\4102380623.py:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for ym in tqdm_notebook(yms):

  0%|          | 0/84 [00:00<?, ?it/s]

In [25]:
df_lumi = pd.concat(dfs, axis=0).to_csv('D:/Work/WB/LDT/countries/SRB/datasets/SRB_luminosity_full.csv', index=False)

In [2]:
bm = pd.read_csv('D:\Work\WB\LDT\countries\SRB\\raw_data\\bm.csv')
bm

          GID_2  year    luminosity
0     SRB.1.1_1  2014  48602.016667
1     SRB.1.1_1  2015  46537.250000
2     SRB.1.1_1  2016  46228.800000
3     SRB.1.1_1  2018  44330.950000
4     SRB.1.1_1  2019  32370.150000
...         ...   ...           ...
1283  SRB.9.4_1  2018  18258.850000
1284  SRB.9.4_1  2019  21028.450000
1285  SRB.9.4_1  2020  19101.600000
1286  SRB.9.4_1  2021  20832.000000
1287  SRB.9.4_1  2022  23306.266667

[1288 rows x 3 columns]

In [3]:
bm = pd.read_csv('D:\Work\WB\LDT\countries\SRB\\raw_data\\bm.csv')
bm = bm[bm['year'].between(2017, 2022)]
bm.to_csv('D:\Work\WB\LDT\countries\SRB\\datasets/SRB_luminosity_full.csv', index=False)

In [4]:
bm = pd.read_csv('D:\Work\WB\LDT\countries\SRB\\datasets/SRB_luminosity_2022.csv')
bm.describe()

         year     luminosity
count   161.0     161.000000
mean   2022.0   49624.210796
std       0.0   64343.191069
min    2022.0    1500.500000
25%    2022.0   15170.850000
50%    2022.0   26742.600000
75%    2022.0   58070.800000
max    2022.0  470141.250000